version: "3"
services:
  mongo:
    image: "mongo:4.0.24-xenial"
    command: mongod --smallfiles
    volumes:
      - "./tmp/db:/data/db"
    ports:
      - "27017:27017"
  rabbit:
    image: "rabbitmq:3.6.5"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis:4.0.12"
    ports:
      - "6379:6379"
  dry-runner:
    build:
      context: .
      dockerfile: Dockerfile-dev
    stop_signal: SIGTERM
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017, rabbit:5672
      APPLICATION_TYPE: "Dry Runner"
    volumes:
      - ./src:/home/node/src
      - ./script:/home/node/script
      - ./test:/home/node/test
    depends_on:
      - mongo
      - rabbit
  runner:
    build:
      context: .
      dockerfile: Dockerfile-dev
    stop_signal: SIGTERM
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017, rabbit:5672
      APPLICATION_TYPE: "Runner"
    volumes:
      - ./src:/home/node/src
      - ./script:/home/node/script
      - ./test:/home/node/test
    depends_on:
      - mongo
      - rabbit
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile-dev
    stop_signal: SIGTERM
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017, rabbit:5672
      APPLICATION_TYPE: "Scheduler"
    volumes:
      - ./src:/home/node/src
      - ./script:/home/node/script
      - ./test:/home/node/test
    depends_on:
      - mongo
      - rabbit
  webhook:
    build:
      context: .
      dockerfile: Dockerfile-dev
    stop_signal: SIGTERM
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017, rabbit:5672
      APPLICATION_TYPE: "WebHook"
    volumes:
      - ./src:/home/node/src
      - ./script:/home/node/script
      - ./test:/home/node/test
    depends_on:
      - mongo
      - rabbit
  worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    stop_signal: SIGTERM
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017, rabbit:5672
      APPLICATION_TYPE: "Worker"
    volumes:
      - ./src:/home/node/src
      - ./script:/home/node/script
      - ./test:/home/node/test
    depends_on:
      - mongo
      - rabbit
