#!/usr/bin/env sh

set -e

script/build

echo "Waiting 5 seconds for services to start..."

sleep 5

echo "Testing codebase..."

if [ ! "$TEST_ONLY" ]; then
exec node -r dotenv/config ./node_modules/nyc/bin/nyc.js --reporter=text --reporter=text-summary ./node_modules/mocha/bin/mocha --recursive "./test/**/*.spec.js"
else
echo "Testing only $TEST_ONLY.spec.js"
echo ""

exec node -r dotenv/config ./node_modules/nyc/bin/nyc.js --reporter=text --reporter=text-summary ./node_modules/mocha/bin/mocha --recursive ./test/$TEST_ONLY.spec.js
fi
