version: '3.1'

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_portal
      MONGO_NON_ROOT_USERNAME: db_portal
      MONGO_NON_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge